backend:
  name: git-gateway

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
      - label: "Home Page"
        name: "home"
        file: "site/data/home.toml"
        fields:
          - {label: Title 2, name: title, widget: string}