backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Projects Page"
        name: "home"
        file: "site/content/projects/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
      - label: "Blog Page"
        name: "home"
        file: "site/content/blog/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
      - label: "About Page"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: "Type", name: "type", widget: "hidden"}
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: Title, name: title, widget: string}
          - {label: Strapline, name: strapline, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: "Text", name: "body", widget: "markdown"}
          - label: Experience
            name: experience
            widget: list
            fields:
              - {label: What, name: what, widget: string}
              - {label: Where, name: where, widget: string}
              - {label: When, name: when, widget: string}
          - {label: "Skills", name: "skills", widget: "text", "required" : false}
      - label: "Contact Page"
        name: "contact"
        file: "site/content/contact.md"
        fields:
          - {label: "Type", name: "type", widget: "hidden"}
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: Title, name: title, widget: string}
          - {label: Strapline, name: strapline, widget: string}
          - {label: "Text", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    filter: {field: "collection", value: "single"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: cover_image, widget: image}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Excerpt", name: excerpt, widget: text, "required" : false}
  - name: "projects"
    label: "Projects"
    folder: "site/content/projects"
    filter: {field: "collection", value: "single"}
    create: true
    fields:
      - {label: "Collection", name: "collection", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Strapline", name: "strapline", widget: "string", "required" : false}
      - {label: "Intro", name: "intro", widget: "markdown", "required" : false}
      - {label: "Summary", name: "summary", widget: "markdown", "required" : false}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Skills", name: "skills", widget: "text", "required" : false}
      - label: Images
        name: images
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Url, name: url, widget: image}