backend:
  name: git-gateway

media_folder: "site/static/image" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "About Page"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Contact Page"
        name: "contact"
        file: "site/content/contact.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Projects Page"
        name: "projects_index"
        file: "site/content/projects.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Project URL", name: "project_url", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "projects"
    label: "Projects"
    folder: "site/content/projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Strapline", name: "strapline", widget: "string", "required" : false}
      - {label: "Intro", name: "intro", widget: "markdown", "required" : false}
      - {label: "Summary", name: "summary", widget: "markdown", "required" : false}
      - {label: "Text", name: "text", widget: "markdown", "required" : false}
      - {label: "Skills", name: "text", widget: "text", "required" : false}
      - label: Images
        name: images
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Url, name: url, widget: image}